version: '3.5'

services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    container_name: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-docker-postgres
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - db
      - redis
    volumes:
      - ./src:/app/src

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    env_file:
      - .env
    ports:
      - '5050:80'
    depends_on:
      - db
  redis:
    image: redis:alpine
    restart: always
    container_name: redis
    env_file:
      - .env
    ports:
      - '6379:6379'
